# Generated by Django 3.2.12 on 2022-06-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROMMeasureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='사용자')),
                ('type', models.CharField(max_length=20, verbose_name='운동 종류')),
                ('value', models.CharField(max_length=5, verbose_name='값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='측정일시')),
            ],
        ),
        migrations.AddField(
            model_name='userinfomation',
            name='ROM_isotonic_1rm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfomation',
            name='ROM_isotonic_end_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfomation',
            name='ROM_isotonic_start_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
