# Generated by Django 3.2.12 on 2022-06-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0002_auto_20220623_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleDataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('grid_size', models.CharField(blank=True, max_length=3, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('hit_count', models.CharField(blank=True, max_length=3, null=True)),
                ('mole_position', models.CharField(blank=True, max_length=3, null=True)),
                ('pane_count', models.CharField(blank=True, max_length=5, null=True)),
                ('hammer_position', models.CharField(blank=True, max_length=3, null=True)),
                ('angle_1', models.CharField(blank=True, max_length=3, null=True)),
                ('angle_2', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
