# Generated by Django 3.2.12 on 2022-06-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0003_moledatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomation',
            name='ROM_isometric_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='등척성 최대근력'),
        ),
    ]
