# Generated by Django 3.2.12 on 2022-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0004_userinfomation_rom_isometric_1rm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomation',
            name='rom_isokinetic_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='등속성 최대근력'),
        ),
    ]
