# Generated by Django 3.2.12 on 2022-06-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0005_userinfomation_rom_isokinetic_1rm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfomation',
            old_name='rom_isokinetic_1rm',
            new_name='ROM_isokinetic_1rm',
        ),
    ]
