# Generated by Django 4.0.6 on 2022-10-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0007_musclefunctionlogdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclefunctionlogdata',
            name='extra',
            field=models.TextField(null=True, verbose_name='추가 데이터'),
        ),
    ]
