# Generated by Django 4.0.6 on 2022-10-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socket', '0008_musclefunctionlogdata_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclefunctionlogdata',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='추가 데이터'),
        ),
    ]
