# Generated by Django 2.2 on 2022-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='step1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='step2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='step3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
