# Generated by Django 2.2 on 2022-03-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220305_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
