# Generated by Django 3.2.12 on 2022-06-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ROM_isokinetic_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='등속성 최대근력'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ROM_isometric_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='등척성 최대근력'),
        ),
    ]
