# Generated by Django 2.2 on 2022-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220629_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isokinetic_b_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='비하인드 랫 풀 다운 등속성 최대근력'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isokinetic_c_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='체스트프레스 등속성 최대근력'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isokinetic_s_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='시티드 등속성 최대근력 로우'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isometric_b_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='비하인드 랫 풀 다운 등척성 최대근력'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isometric_c_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='체스트프레스 등척성 최대근력'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isometric_s_1rm',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='시티드 로우 등척성 최대근력'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_b_end_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_b_start_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_c_end_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_c_start_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_s_end_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_s_start_ypos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
