# Generated by Django 4.0.6 on 2022-07-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220706_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_b_1rm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_c_1rm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isotonic_s_1rm',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
