# Generated by Django 4.0.6 on 2022-10-13 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_userinfo_isotonic_b_1rm_userinfo_isotonic_c_1rm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMuscleFunctionRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='운동 종류')),
                ('start_positions_y', models.TextField(blank=True, max_length=5, null=True, verbose_name='시작지점 계급값')),
                ('end_positions_y', models.TextField(blank=True, max_length=5, null=True, verbose_name='종료지점 계급값')),
                ('left_angles', models.TextField(blank=True, max_length=5, null=True, verbose_name='좌 팔꿈치 계급값')),
                ('right_angles', models.TextField(blank=True, max_length=5, null=True, verbose_name='우 팔꿈치 계급값')),
                ('did_at', models.DateTimeField(auto_now_add=True, verbose_name='측정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
