# Generated by Django 4.0.6 on 2022-10-13 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usermusclefunctionrange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='isotonic_b_end_ypos',
            new_name='b_end_ypos',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='isotonic_b_start_ypos',
            new_name='b_start_ypos',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='isotonic_c_end_ypos',
            new_name='c_end_ypos',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='isotonic_c_start_ypos',
            new_name='c_start_ypos',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='isotonic_s_end_ypos',
            new_name='s_end_ypos',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='isotonic_s_start_ypos',
            new_name='s_start_ypos',
        ),
    ]
