# Generated by Django 4.0.6 on 2022-10-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userinfo_l_end_ypos_userinfo_l_start_ypos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermusclefunctionrange',
            name='y_positions',
            field=models.TextField(blank=True, null=True, verbose_name='각도 계급값'),
        ),
        migrations.AlterField(
            model_name='usermusclefunctionrange',
            name='end_positions_y',
            field=models.TextField(blank=True, null=True, verbose_name='종료지점 계급값'),
        ),
        migrations.AlterField(
            model_name='usermusclefunctionrange',
            name='left_angles',
            field=models.TextField(blank=True, null=True, verbose_name='좌 팔꿈치 계급값'),
        ),
        migrations.AlterField(
            model_name='usermusclefunctionrange',
            name='right_angles',
            field=models.TextField(blank=True, null=True, verbose_name='우 팔꿈치 계급값'),
        ),
        migrations.AlterField(
            model_name='usermusclefunctionrange',
            name='start_positions_y',
            field=models.TextField(blank=True, null=True, verbose_name='시작지점 계급값'),
        ),
    ]
