# Generated by Django 4.0.6 on 2022-10-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_usermusclefunctionrange_y_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermusclefunctionrange',
            name='y_positions',
            field=models.TextField(blank=True, null=True, verbose_name='지점 계급값'),
        ),
    ]
