# Generated by Django 4.0.6 on 2022-11-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_usermusclefunctionrange_y_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
