# Generated by Django 2.2.9 on 2023-09-14 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_externalexerciselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalexerciselog',
            name='excericse',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='운동 종류'),
            preserve_default=False,
        ),
    ]
